### ISSUE TITLE
Add support for custom binaries

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [davidmarkclements/0x#10]
First of all: (In general) cool work. Always had something like this in mind, but never went for the long distance. Much appreciated.

***

Currently, by looking at the implementation, custom binaries, like when you'd work on node core, don't work. I'd like to be able to run `0x ./node example.js` for benchmarking purposes, whereas `./node` resolves to the node binary in my current working directory.

If you know where to include this real quick, I'd appreciate the change. Otherwise I'll send in a PR at the beginning of the week

**Comment by davidmarkclements** [comment]
thanks man - kudos to nearForm also for supporting me to do it

you make it a good point - incoming

**Comment by eljefedelrodeodeljefe** [comment]
Ah, only now I was seeing that you already provided this feature in your readme. I am not, but I think it didn't work, because I tried it with a compiled binary that definitely had a feature the normal binary hasn't. But with the current version this then would throw, because the respective binary hasn't included it. 

It hink I fixed this in the following PR. If I am wrong please ignore it.

**Comment by davidmarkclements** [comment]
no no - I just added that to readme. trying to publish but can't because I'm hotspotting on a train in Ireland - I've already added the functionality in 27edd69 (I think - can you pull from master and check - if not we'll take your PR)

**Comment by eljefedelrodeodeljefe** [comment]
Tried, didn't work for me. :( . Don't wanna bother you on a Sunday even, sorry.

**Comment by davidmarkclements** [comment]
nah it's okay - travelling back from a conf at mo - working anyway - I'll merge your PR

**Comment by eljefedelrodeodeljefe** [comment]
Awesome. Tell you, this lib is so useful. Happy to contribute some.
