### ISSUE TITLE
v3: Update jsdom

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/0x#104]
The used version depends on a version with a low-severity security isse: https://snyk.io/org/mcollina/project/4ad6c32c-1e38-43a9-927f-6eebbcfaca20?disclosure=all&severity=high&severity=medium&severity=low.

**Comment by davidmarkclements** [comment]
Jsdom is removed in v4 - it's used for svg rendering - but fair play we'll have to upgrade in v3 and.. v2... and v1

**Comment by davidmarkclements** [comment]
fixed in v3 https://github.com/davidmarkclements/0x/commit/5bea6bcbf7bb0e990798614016d1035752afaef7
published as 3.3.1
and v2 https://github.com/davidmarkclements/0x/commit/f1c4dd6ba1ea00095e57563aecabc1bec20151a6
published as 2.5.4
