### ISSUE TITLE
0x for flame graph of mocha tests

### ISSUE THREAD

**Issue by chrisveness** [davidmarkclements/0x#112]
Is it possible to use 0x to generate flame graphs of [mocha](https://www.npmjs.com/package/mocha) tests?

To complicate things, I'm using [esm](https://www.npmjs.com/package/esm), so my test command is `mocha --exit -r esm test/*.js`.

I thought I might have had it working by using `0x -- node $(which mocha) --exit -r esm test/*.js` but the flame graph had basically nothing in it.

**Comment by bengl** [comment]
This is most likely because mocha spawns a subprocess (`_mocha`) that does the actual work.

You *might* be able to get this to work with:

```
$ 0x -- node -r esm $(which _mocha) --exit test/*.js
```

Note that `-r esm` is being passed to `node`, rather than `_mocha`.

**Comment by davidmarkclements** [comment]
Probably solvable with #97 (although good point @bengl on the child process case)

**Comment by chrisveness** [comment]
@bengl using `_mocha` seems to be what I needed – thanks for the suggestion.

Now I can look forward to delving into and making sense of the flame graphs!

**Comment by dschuessler** [comment]
@chrisveness Would you mind posting here _how_ you used `_mocha`, that is: Which command (pattern) did you use to actually get flamegraphs of mocha runs? Adapting @davidmarkclements suggestion to my situation unfortunately fails.
