### ISSUE TITLE
Broken in Firefox

### ISSUE THREAD

**Issue by mafintosh** [davidmarkclements/0x#124]
Just a reminder that the ui doesn't work in firefox. Perhaps we should add a notice that this is chrome only?

**Comment by davidmarkclements** [comment]
The readme specifies chrome as a requirement and mentions other browsers will have reduced functionality

**Comment by mafintosh** [comment]
Can we make it show a message in FF that you should use chrome? It's just shows a white page basically which is confusing

**Comment by davidmarkclements** [comment]
Yep can do as an interim solution

**Comment by kachkaev** [comment]
What exactly is not working in FF? I can't see any errors in the console or in network logs, the page is just blank:
 
<img width="754" alt="screen shot 2018-04-25 at 15 09 18" src="https://user-images.githubusercontent.com/608862/39251226-adfbd036-489a-11e8-9543-af7757183f40.png">

This reminds me of times when the latest and the coolest websites could run only in IE6! 😅

**Comment by davidmarkclements** [comment]
fixed in https://github.com/davidmarkclements/0x/pull/131

**Comment by goto-bus-stop** [comment]
Yeah I did not get the blank page issue in FF 62, just some style issues. Maybe it was already fixed in newer FF versions
