### ISSUE TITLE
Failing with JSON parse error

### ISSUE THREAD

**Issue by emirotin** [davidmarkclements/0x#132]
The program I'm trying to profile is a node script, normally I run it like
```
botpress start
```

Or more specifically in this case
```
"start": "NODE_ENV=production LOG_LEVEL=info DATABASE=postgres DATABASE_URL=postgres://x:y@localhost:5432/z node ./node_modules/.bin/botpress start"
```

Which works.

I am also able to manually gather the profiling info by running
```
"start-perf": "rm -f isolate* && NODE_ENV=production LOG_LEVEL=info DATABASE=postgres DATABASE_URL=postgres://x:y@localhost:5432/z node --prof ./node_modules/.bin/botpress start"
```

My 0x command correspondingly looks like
```
"start-0x": "NODE_ENV=production LOG_LEVEL=info DATABASE=postgres DATABASE_URL=postgres://x:y@localhost:5432/z 0x -- node ./node_modules/.bin/botpress start"
```

And I'm getting

```
🔥  ProfilingSyntaxError: Unexpected token : in JSON at position 2
    at JSON.parse (<anonymous>)
    at Pipe.channel.onread (internal/child_process.js:470:28)
```

Any idea why?
I'm not seeing the detailed stack so I'm not even sure if it's coming from `0x` itself or from my program being ran in some unusual way (and thus maybe not being able to find some JSON file by relative path?)

**Comment by davidmarkclements** [comment]
it looks like a clash between botpress and 0x - in particular I'm guessing <https://github.com/davidmarkclements/0x/blob/master/lib/preload/redir-stdout.js> would be a good place to be suspicious of. Botpress might be doing something similar.

**Comment by davidmarkclements** [comment]
The reason for this btw is that the V8 flags tend to write to stdout from the C layer, there's no way to control this and filtering V8 log info from user stdout is essentially impossible

**Comment by emirotin** [comment]
Hm, I don't think we're doing anything fancy with the streams in botpress. We do use winston with colored output for logging but that should be it. 

Want me to share the sample repro project?

**Comment by mcollina** [comment]
Sorry for the long delay, yes please share it!

**Comment by emirotin** [comment]
Please see https://github.com/emirotin/demo-botpress-0x
It's not the absolutely minimal example, let me know if further reduction is needed, but it's _pretty minimal_ for `botpress`

Check the `scripts` section of package.json. The "normal" start and native node profiling work for me, 0x fails.

`botpress` is our library we're currently trying to profile/optimize and the "naked" node profiling report is not of much help to me so I was hoping 0x would give me more JS-centric graph

**Comment by mcollina** [comment]
I'm getting:

```
$ npm run start-0x

> vanilla@1.0.0 start-0x /Users/matteo/Repositories/demo-botpress-0x
> NODE_ENV=production 0x -- node ./node_modules/.bin/botpress start

🔥  Profilingmodule.js:549
    throw err;
    ^

Error: Cannot find module '/Users/matteo/Repositories/demo-botpress-0x/node_modules/.bin/botpress'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

🚫  Target subprocess error, code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vanilla@1.0.0 start-0x: `NODE_ENV=production 0x -- node ./node_modules/.bin/botpress start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vanilla@1.0.0 start-0x script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matteo/.npm/_logs/2018-07-12T17_57_14_849Z-debug.log
~
```

**Comment by emirotin** [comment]
That's strange. You've surely `npm install`ed before running. In which case there should be `botpress` script in `./node_modules/.bin`

**Comment by mcollina** [comment]
I did `npm i`. I think there might be some dependency missing.

**Comment by emirotin** [comment]
The dependency is `botpress` itself, I think it's there. Does it work with normal `npm start`?

**Comment by mcollina** [comment]
same thing


Il giorno ven 13 lug 2018 alle ore 13:15 Eugene Mirotin <
notifications@github.com> ha scritto:

**Comment by mcollina** [comment]
I was finally able to install it using yarn and I was able to reproduce.

**Comment by goto-bus-stop** [comment]
I get this stack trace after installing [trace](https://npmjs.com/package/trace) and [clarify](https://npmjs.com/package/clarify), then using `NODE_OPTIONS="-r trace -r clarify" npm run start-0x`:
```
/home/goto-bus-stop/Code/nearform/demo-botpress-0x/node_modules/botpress/lib/webpack:/src/botpress.js:477
      cluster.fork().on('message', receiveMessageFromWorker)
              ^
SyntaxError: Unexpected token : in JSON at position 2
    at botpress.start (/home/goto-bus-stop/Code/nearform/demo-botpress-0x/node_modules/botpress/lib/webpack:/src/botpress.js:477:15)
    at Command.module.exports (/home/goto-bus-stop/Code/nearform/demo-botpress-0x/node_modules/botpress/lib/webpack:/src/cli/start.js:95:9)
    at Command.listener (/home/goto-bus-stop/Code/nearform/demo-botpress-0x/node_modules/commander/index.js:315:8)
    at Command.parseArgs (/home/goto-bus-stop/Code/nearform/demo-botpress-0x/node_modules/commander/index.js:651:12)
    at Command.parse (/home/goto-bus-stop/Code/nearform/demo-botpress-0x/node_modules/commander/index.js:474:21)
```

I guess it's because 0x doesn't support `cluster`?

**Comment by goto-bus-stop** [comment]
agree: https://github.com/davidmarkclements/0x/pull/155
