### ISSUE TITLE
0x may exit without generating flamegraph on SIGINT

### ISSUE THREAD

**Issue by vizv** [davidmarkclements/0x#136]
With node v8.11.3 installed with nvm in Gentoo recently, 0x (4.1.0) occasionally exit without generating flamegraph on SIGINT (generated with Ctrl + C).

I did some investigation, and I think the issue is related to this line:

https://github.com/davidmarkclements/0x/blob/cbd5c309d0adea0d2cec8d7bf8ccb967670ebd4e/platform/v8.js#L49

I tried to put the following debug print just before the `Promise race`:

```javascript
process.on('SIGINT', () => console.log('|SIGINT|'))
```

and when I press Ctrl + C it prints two `|SIGINT|` however it won't exit without generating flamegraph anymore.

I have no idea why it emits two `SIGINT` events to `process` and how to fix this issue (or is it just me)?

**Comment by mcollina** [comment]
Can you please include the js file that trigger this problem? So I’ll have an easier time reproducing this.

Also, is this happening with Node 8.11.2 (or earlier)? Is this happening only on gentoo?

**Comment by vizv** [comment]
I think it's related to our source code, but unfortunately I can't disclose those source.
I'm trying to come up with an example to reproduce this issue, I haven't tried on 8.11.2 or earlier versions and I don't think it's gentoo related since I use nvm to install the binary.

**Comment by vizv** [comment]
@mcollina I can reproduce now, it's npm related

I have created a `test.js`:

```javascript
var express = require('express')
var app = express()
app.listen(3000)
```

then modify `package.json`, add the following script:

```json
  "scripts": {
    "profiling": "0x test.js"
  },
```

and run `npm run profiling` will occasionally reproduce the issue, run `0x test.js` without npm works fine all the time

**Comment by vizv** [comment]
Finally I found it, npm generates the second `SIGINT` here:

https://github.com/npm/npm-lifecycle/blob/62db5e4270ecdc7730b607a949df972be6d61f01/index.js#L345

However I have no idea how to resolve it, I think I'm going to avoid using npm run 0x for now

**Comment by davidmarkclements** [comment]
excellent detective work @vizv  - so it seems that the there's an intermittent problem (possibly in node core, possibly in npm's code) with sending a sigint to the child process.

**Comment by davidmarkclements** [comment]
@vizv does your problem persist with latest release, as per this pr https://github.com/davidmarkclements/0x/pull/138 ?

**Comment by vizv** [comment]
@davidmarkclements No, it's more like an npm issue that sends two SIGINTs. With the latest version (4.1.2) the problem persist on our code-base or on the example above

I'll write a shell script that check how many SIGINTs npm sends, and save it as `foo.sh`, give it executable permission:

```bash
#!/bin/sh

COUNTER=0

handle() {
  COUNTER=$((COUNTER + 1))
  echo "Got SIGINT ${COUNTER} times"
}

trap handle INT

while true; do sleep 20; done
```

then modify package.json, add the following script:

```json
  "foo": "./foo.sh"
```

and when I press Ctrl + C this time, it says only one SIGINT was sent and the send time SIGTERM kills it as expected (which is how npm is implemented).

Now I'm really confused, could you reproduce the issue on your side?

**Comment by vizv** [comment]
Well, I wrote an js version as well, and surprisingly npm sends two SIGINT to node.js scripts.

Put this file in `./node_modules/.bin/bar`, give it executable permission:

```javascript
#!/usr/bin/env node

const { spawn } = require('child_process')

let counter = 0

process.on('SIGINT', () => console.log('SIGINT: ', ++counter));

const proc = spawn('sleep', ['10'], {detached: true})

proc.on('exit', () => console.log('done'))
```

then modify package.json, add the following script:

```json
  "bar": "bar"
```

after `npm run bar`, press Ctrl + C, it prints

```
^CSIGINT:  1
SIGINT:  2
```

this time, and the second Ctrl + C kills it

So it IS an npm bug?

**Comment by davidmarkclements** [comment]
Looks like it yeah, but also we should be better handling multi sigint (if that's causing the issue)

**Comment by vizv** [comment]
@davidmarkclements handling multi SIGINT will be great!

I also write a node.js script to confirm it's not `child_process.spawn()` sends two SIGINTs, I'll do some investigation on npm later

**Comment by mcollina** [comment]
The reason why handle only _one_ `'SIGINT'` is because we must avoid a case where it's hard to stop the process in the case it hangs. This would lead to a bad user experience in the case of a bug.
I also cancel the flamegraph generation very soon.

Maybe we could detect if we are been called from npm.

**Comment by goto-bus-stop** [comment]
In my setup I get even stranger behaviour. I'm getting a variation the problem mentioned in the OP intermittently with Zsh 5.5, Node 8 and npm 6 … (there is also an issue where if the subprocess is stuck in an infinite loop it keeps running in the background after 0x starts generating a flame graph, but that's a separate problem)

I added some logging to npm-lifecycle (prefixed «) and 0x (prefixed »), sometimes it all works and logs received sigints, and sometimes this happens:

```
> 0x@4.1.5 test ./0x
> ./cmd.js app
🔥  Profiling
» added sigint, sigterm, exit
^C« procInterupt
```

procInterupt in npm-lifecycle sends a SIGINT to the child process but the event handler doesn't fire in the child…? That seems so strange that it feels like I _must_ be doing something wrong but pretty stumped as to what that could be :sweat:
