### ISSUE TITLE
npm i -g 0x fails

### ISSUE THREAD

**Issue by tuananh** [davidmarkclements/0x#139]
```
EEXIST: file already exists, symlink '../jsonstream2/bin/jsonstream.js' -> '/Users/me/.npm/lib/node_modules/0x/node_modules/.bin/jsonstream'
npm ERR! File exists: ../jsonstream2/bin/jsonstream.js
npm ERR! Move it away, and try again.
```

i'm using npm 5.6.0

is there any idea why it happens?

**Comment by davidmarkclements** [comment]
this is a problem with your npm client. Please try following npms instructions, if that fails open an issue on the `npm` repo, try a different npm version.
