### ISSUE TITLE
Duplicated JavaScript code in HTML

### ISSUE THREAD

**Issue by shuhei** [davidmarkclements/0x#147]
Hi, thanks for this great tool!

I found that the code for `hsl-to-rgb-for-reals` appears three times and `d3-fg` twice in `flamegraph.html`.

[lib/render.js](https://github.com/davidmarkclements/0x/blob/v4.1.4/lib/render.js#L61-L63) builds three standalone bundles and concatenates them.

1. `hsl-to-rgb-for-reals` as `hsl`
2. `d3-fg` as `fg`
3. `../visualizer` as `visualizer`

It seems that the bundle 2 already has `hsl-to-rgb-for-reals` in it, and the bundle 3 has `hsl-to-rgb-for-reals` and `d3-fg` in it. I removed the first two bundles from my `flamegraph.html` and it still worked. Why does `0x` add the first two standalone bundles?

**Comment by davidmarkclements** [comment]
Nice spot - if you'd like to send a PR I'd definitely welcome it

**Comment by shuhei** [comment]
Sure! Made one https://github.com/davidmarkclements/0x/pull/148
