### ISSUE TITLE
Node master does not generate the JSON file

### ISSUE THREAD

**Issue by BridgeAR** [davidmarkclements/0x#157]
If I am not mistaken there is a bug in V8 that prevents the JSON file from being generated with Node core master.

I am relatively confident that it was already fixed on V8 side and I'll try to see if the patch indeed fixes the issue.

**Comment by mcollina** [comment]
Which file does not generate?

Thanks, let me know!

**Comment by BridgeAR** [comment]
The log file was not correctly produced on a older v8 version. This seems to be resolved.
