### ISSUE TITLE
Entries should have more than a single type

### ISSUE THREAD

**Issue by BridgeAR** [davidmarkclements/0x#164]
Right now all stacks can have a single type such as `cpp`, `core`, `init` etc. Sadly, it's only possible to add a single type instead of multiple ones. However, in a couple of cases multiple types could apply to a single stack.

It does seem to require a good portion of rewriting internal logic to change this tough. If there's a simple way to achieve this, please let me know.

**Comment by mcollina** [comment]
Can we document such cases?

**Comment by BridgeAR** [comment]
You mean documenting in what cases this could apply? E.g., `v8` and `cpp`. `init` and `core`...

**Comment by mcollina** [comment]
Let's say we have a hierarchy for now if more apply:

init > v8 > cpp > core

**Comment by BridgeAR** [comment]
We have such a hierarchy at the moment. And it is exactly as you want this order.

**Comment by mcollina** [comment]
Oh, ok :D.
