### ISSUE TITLE
Is 0x filename.js similar to npm start filename.js ?

### ISSUE THREAD

**Issue by gtzinos** [davidmarkclements/0x#183]

**Comment by mcollina** [comment]
I do not think so. It's not exactly clear what you would like to achieve either. Can you please clarify you question?

**Comment by gtzinos** [comment]
Hello @mcollina, in my case I have a project which I deploy it with command "npm start index.js". 

What command do I have to use in your library to run like 'npm start '? Is 0x index.js enough?

**Comment by mcollina** [comment]
What have you got in `package.json` regarding the `start`  script?

**Comment by gtzinos** [comment]
I have the npm start command

**Comment by BridgeAR** [comment]
You have to run `node cmd.js index.js`. That is likely what you want.

**Comment by gtzinos** [comment]
thanks a lot!
