### ISSUE TITLE
Failing to export graph when an app has an infinity loop, but is what i would like to find.

### ISSUE THREAD

**Issue by gtzinos** [davidmarkclements/0x#184]
"Closing subprocess is taking a long time, it might have hung. Press Ctrl+C again to force close"

I pressed Ctrl + C and then it tries forever 

"Process exited, generating flamegraphbuffer"

* i used 0x --collect-only index.js

**Comment by mcollina** [comment]
Which version are you using? Can you include the contents of index.js?

**Comment by BridgeAR** [comment]
I only recall this error on Node 10.10.

**Comment by gtzinos** [comment]
I used node 8.11

Also node native profiling failed in this version (if it helps) but when i used node 8.9.4, worked.

**Comment by gtzinos** [comment]
I fixed it thank you! I used node 8.9.4.
