### ISSUE TITLE
Do not classify net _tickCallback as INIT

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/0x#186]
executing `process.nextTick` is currently misrecognized as INIT in all cases. However, we should not recognize it as INIT after boot has completed.

cc @BridgeAR

**Comment by BridgeAR** [comment]
I mentioned that in the PR that added esm support: https://github.com/davidmarkclements/0x/pull/178#issue-217449654. There is no specific boot phase that is detected. It is just all parts that have something to do with booting up. I'll filter the next ticks now.

**Comment by mcollina** [comment]
Thanks!

Il giorno lun 8 ott 2018 alle ore 15:30 Ruben Bridgewater <
notifications@github.com> ha scritto:
