### ISSUE TITLE
do not throw on process exit with non-zero code

### ISSUE THREAD

**Issue by ovhemert** [davidmarkclements/0x#198]
Related to confirmed bug in nearform/node-clinic#73.

When client process terminates with an exit code > 0 like process.exit(1), an error is thrown by flame / 0x. Clinic terminates, and trace event file is not moved to logging directory. Terminating the client process this way could be intentional and trace output is still useful.

Flame / 0x should report the error to the console but not throw. And still move trace event file to the logging directory for visualisation by Clinic.

**Comment by davidmarkclements** [comment]
this is actually a behavioural change, the original decision to throw on non-zero exit code
was based on the assumption that if an app crashed then it's got bigger problems than performance.
Exiting with non-zero means there's a problem.

To accept this PR I think this would need to be a major release

@mcollina what do you think?

**Comment by davidmarkclements** [comment]
no scratch that, minor release since it's backwards compatible

**Comment by mcollina** [comment]
released in v4.6.0.
