### ISSUE TITLE
error on Windows

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/0x#202]
```
Error: Encountered an unparseable frame "(anonymous) D:\a
```

**Comment by AlanSl** [comment]
Can you post the full file / directory path (what's being chopped after the `a`) and I'll add it to the edge cases / tests PR I'm working on, which includes a lot of funky stuff with Windows paths, Unicode etc

**Comment by AlanSl** [comment]
Also which version of Node? The fix for Windows path separators being treated as escape patterns has some issues in Node 8 and different issues in Node 11 that aren't in Node 10

**Comment by davidmarkclements** [comment]
I spoke to @mcollina just now – it's Node 10 (and Windows 10)

if it's in the latest 0x release, https://github.com/davidmarkclements/0x/pull/201 might be related

**Comment by mcollina** [comment]
I think the regexp introduced in https://github.com/davidmarkclements/0x/pull/193/

is not complete/broken on Node 10.

cc @mafintosh

**Comment by mcollina** [comment]
I think this line https://github.com/davidmarkclements/0x/blob/1cfbc5686c8f8cc48bc500a8d31a7c61f00d770a/lib/v8-log-to-ticks.js#L36

needs to change the pattern from `:\\` to `:\`

**Comment by AlanSl** [comment]
There's a bunch of issues with that regex that are fixed in the PR I'm working on, for instance it gets confused by unicode chars like //u12a3 - but in my tests I've only seen that happen on Node 8. What's the text after the `a` in your path?

Maybe it's mistakenly parsing something like D:/a/n as a newline?

**Comment by mcollina** [comment]
That happens on Azure pipelines. There is nothing else.

**Comment by davidmarkclements** [comment]
was this ever resolved?
