### ISSUE TITLE
bug: linux cmd line argument parsing does not allow additional arguments

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [davidmarkclements/0x#21]
When I was seeing this right, having the following commands on linux give you `file --prof (cannot remember actual string) not existing`. I suppose shifting the arguments doesn't work properly currently.

```
DEBUG=0x ./cmd.js examples/simple/index.js
./cmd.js node examples/simple/index.js
```

**Comment by davidmarkclements** [comment]
this is a priority

**Comment by eljefedelrodeodeljefe** [comment]
I'll look into it at the end of the day. This is likely an easy fix.

**Comment by davidmarkclements** [comment]
@eljefedelrodeodeljefe is this still a problem with 2.2.6? I'm not finding any problems with linux and 0x, node or js file args

**Comment by eljefedelrodeodeljefe** [comment]
Working fine!
