### ISSUE TITLE
EEXIST: file already exists, uv_pipe_open

### ISSUE THREAD

**Issue by vectronic** [davidmarkclements/0x#210]
Hello,

Awesome tool! However I am having trouble using it with the following:

```
0x version 4.7.4
npm 6.9.0
node 11.11.0
FreeBSD 11.1
```

I am trying to launch as follows:

```
0x /usr/local/bin/homebridge -U /home/homebridge/.homebridge
```

Where homebridge is a node JS app https://github.com/nfarina/homebridge and the args are just where my config for it sit.

About half way through the homebridge startup I get this:

```
net.js:276
    err = this._handle.open(fd);
                       ^

Error: EEXIST: file already exists, uv_pipe_open
    at new Socket (net.js:276:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/0x/lib/preload/redir-stdout.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:930:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:221:5)
```

Any suggestions on how to go about investigating this further?

Thanks

**Comment by mcollina** [comment]
I would recommend updating your Node.js version to the latest in the 6.x release or 8.x or 10.x.
Can you please verify if the same happens on a Mac OS X, Linux or Windows machine? We are not really supporting FreeBSD here - I don't have that installed to test this tool there.

Also, can you please try the following syntax `0x -- /path/to/node my-app.js`?

**Comment by vectronic** [comment]
Update on this:

I tried the same version of 0x on:

npm 6.4.1
node 10.15.3
macOS 10.14.3 

and got the same error.

However Homebridge has a plugin architecture and I had a number of plugins configured. By removing them one by one I narrowed it down to this one causing the issue:

https://github.com/oznu/homebridge-config-ui-x

I'm not au fait enough on 0x nor that plugin to know what exactly within it was causing the issue.

For now, without that plugin installed I still see the perf issues I was hoping to tackle with 0x, so my particular problem is solved.

Not sure if you want to explore more why that plugin's codebase causes 0x to bork. You've probably got other things to be doing....

Thanks.

**Comment by mcollina** [comment]
It's the use of child processes. We currently do not support that.

**Comment by vectronic** [comment]
Ok great - all makes sense then - thanks for your help.

**Comment by yunfengsay** [comment]
Had you solved this problem?

**Comment by vectronic** [comment]
> Can you tell how can you solved this ? @vectronic

I stopped using 0x because it didn’t support NodeJS  case which makes use of child processes.
