### ISSUE TITLE
Profile from Chromium 75 not loading with --visualize-cpu-profile

### ISSUE THREAD

**Issue by cmdcolin** [davidmarkclements/0x#215]
I used the "Javascript profiling" tab in Chromium 75 on linux

```
🔥  Creating flamegraph from v8 profile CPU-20190730T212046.cpuprofileTypeError:
🚫  Cannot read property 'children' of undefined
    at convert (/usr/lib/node_modules/0x/lib/cpu-profile-to-tree.js:5:33)
    at cpuProfileToTree (/usr/lib/node_modules/0x/lib/cpu-profile-to-tree.js:25:21)
    at render (/usr/lib/node_modules/0x/lib/render.js:26:13)

```

The resulting file failed to load. I am uploading it here just for reference

[CPU-20190730T212046.cpuprofile.gz](https://github.com/davidmarkclements/0x/files/3449383/CPU-20190730T212046.cpuprofile.gz)

The format of the profile format always seems to change at chromes whim unfortunately.

**Comment by davidmarkclements** [comment]
did you gzip it yourself or did it come that way? did you try gunzipping it?

**Comment by cmdcolin** [comment]
I gzipped it for upload. There might be a difference between this cpuprofile and the sample cpuprofile in this repo. I did obtain it from the "Javascript profiling" tab of Chromium

![2019-07-30-211726_3840x2160_scrot](https://user-images.githubusercontent.com/6511937/62221527-c642dd00-b37f-11e9-9e66-c5fc45474a5b.png)

The samples.cpuprofile in this repo can also be loaded into https://thlorenz.com/flamegraph/web/ but it appears similarly to have changed and was tracked here https://github.com/thlorenz/flamegraph/issues/21

**Comment by cmdcolin** [comment]
If this is very similar to https://github.com/thlorenz/flamegraph/issues/21 that this is probably an enhancement type issue rather than a bug (but it would be very cool to have)

**Comment by cmdcolin** [comment]
Found a tool that can work with latest chrome profiling JSON http://jamie-wong.com/post/speedscope/
