### ISSUE TITLE
0x for production environment

### ISSUE THREAD

**Issue by jeyarajcs** [davidmarkclements/0x#216]
This is not an issue... Just I want help.

I am using NodeJS for my application in production. Now my web application getting more number of concurrent users and http requests. When the load getting increased  the nodejs process takes more memory.
When I check through PM2, it shows upto **2GB**. But when the load getting reduced, the memory is not falling back. It stays in **1.5GB** above. If I **restart PM2**, then it reduce to **150MB**.
So, I clearly know there is memory leak. 
We tried some lead testing in dev environment, But not able to get root cause.

My request is, How to identify such memory leak root cause in production environment without affect any live process. Will **0x** help such cases?

My server will be heavily loaded during day time, But in night no transaction at all. Is there any possibility to get dump of memory leak during such times?

Thanks...

**Comment by davidmarkclements** [comment]
hey there 0x is for CPU profiling only, and recommended to only be used in dev/ci/staging not in production
