### ISSUE TITLE
Minor Comment

### ISSUE THREAD

**Issue by odax-ethan** [davidmarkclements/0x#219]
Been using 0x recently and have found it very useful. Thank you for the time you've put into this project. 

One quick thing I found an issue that probably affects other users. 
Is the command for generating the flame graph is CTRL-C which is often the same command to terminate a terminal "operation" (not sure if that the right term).  

The reason this is an issue:
 In my case, my express server terminates even when I select N to not terminate the batch job. I realize this is not something you can fix here but by avoiding CTRL-C this problem wouldn't exist.

It may make sense to change the generate Flamegraph to CTRL-F or CTRL-G.

**Comment by davidmarkclements** [comment]
this is based on SIGINT - on linux/macOs CTRL-C is the SIGINT. If you don't want your server to close on CTRL-C you can handle the SIGINT signal independently.

It's deliberately the same as closing the process, as you create the flamegraph when you're done profiling the server. 

You can generate flamegraphs in two steps: use the `--collect-only` flag and then use `0x --visualize-only <pid>.0x` where pid was the pid of your process

**Comment by odax-ethan** [comment]
Thank you for the clarification.
