### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Jero786** [davidmarkclements/0x#228]
Hello!

Thank for your library, it's such amazing. 
The only problem that I'm facing is about I'm not able to define an absolute path different than `__dirname`.

```js
async function captureFlameGraph (timestamp) {
    const fileName = '/Users/jero/projects/ipsy/shopper-web-3/server/dumps'
    const opts = {
        argv: [path.join(__dirname, 'index.js'), '--output-dir' ,`"/some_path_here_doesnt_work"`], // <---- seting output-dir it doesn't effect nothing at all.
        workingDir: __dirname, // <------- That path it's working 
        workingDir: // '/other_absolute_path/' <------ Throw exception, please take at the bottom*
    };
    try {
        const file = await zeroEks(opts);
    } catch (e) {
        console.error(e)
    }
}
```

Debugging internally seems like the absolute path that we define, it's not creating the `isolate-..-v8.log`, so when check if exit throws en exception in the following line: https://github.com/davidmarkclements/0x/blob/master/platform/v8.js#L110, after that, arrive in the line: https://github.com/davidmarkclements/0x/blob/master/index.js#L83 and pass the second argument as a `undefined`, because it didn't found isolate log in the workingDir. And finally, in the join method, we have the `undefined` unwanted.

![image](https://user-images.githubusercontent.com/1815487/76801804-1f4b6e00-67b5-11ea-9599-84524b7ddb99.png)

That produces the error :(

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at join (path.js:1147:7)
    at v8.catch (/Users/jero/projects/ipsy/shopper-web-3/node_modules/0x/index.js:85:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Anyone could help me on that?

**Comment by Jero786** [comment]
Here I mead the fix of this issue here: https://github.com/davidmarkclements/0x/pull/229

**Comment by divmgl** [comment]
So is this library completely broken? I can't get a simple use-case to run from the `README.md`.

**Comment by SukkaW** [comment]
> So is this library completely broken? I can't get a simple use-case to run from the `README.md`.

Yes.
