### ISSUE TITLE
Compatibility with node-source-map-support

### ISSUE THREAD

**Issue by donmccurdy** [davidmarkclements/0x#235]
I'm profiling a project written in TypeScript, and so the references in the flamechart are all lines in a single bundled file. I already use https://github.com/evanw/node-source-map-support to get useful stack traces in unit tests — is there a way that node-source-map-support (or something similar) could be used to show source-mapped filenames in the flamechart too?

**Comment by Zikoel** [comment]
Hi, I tried to analyze a TS program but instead of create a bundle (maybe you use webpack or others) I have compiled it with `tsc` this make the result a little bit more readable have you tried this way?
