### ISSUE TITLE
Environment variable is undefined

### ISSUE THREAD

**Issue by jeromecovington** [davidmarkclements/0x#24]
I can run this command with `node`, but when I run it with `0x` it seems that `process.env.BENCHMARK` is `undefined`? Do environment variables not get picked up by `0x`?

```
> env BENCHMARK='server/models/timeline' ./node_modules/.bin/0x node benchmark/single.js
module.js:339
    throw err;
    ^

Error: Cannot find module './undefined'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/jtkc/example/benchmark/single.js:3:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
Profiling
```

**Comment by davidmarkclements** [comment]
ooh interesting, we need to pass environment vars through to the sub process I think

**Comment by davidmarkclements** [comment]
you might be able to work around temporarily with
```
export BENCHMARK='server/models/timeline'
0x benchmark/single.js
```

**Comment by davidmarkclements** [comment]
@jeromecovington I'm not reproducing your problem here

test.js:
```js
console.log(process.env.FOO)
```
```sh
$ env FOO='ok' 0x -d 0 test.js
ok

file:///Users/davidclements/z/0x/profile-8161/flamegraph.html
```

(using -d 0 set remove delay, has no effect on env recog.)

could you try the same isolated case?

**Comment by jeromecovington** [comment]
I am getting undefined, but I am running the binary locally, is that the issue?
`> env FOO='ok' ./node_modules/.bin/0x -d 0 test.js`

**Comment by davidmarkclements** [comment]
no it's working for me - what version of 0x and what version of node are you running?

0x doesn't have a -v flag, but to get the version: 

```
$ npm explore 0x 
bash-3.2$ grep version package.json
```

Going to add a -v flag

**Comment by jeromecovington** [comment]
node 4.2.3
0x 2.2.4

**Comment by davidmarkclements** [comment]
what OS?

**Comment by davidmarkclements** [comment]
ah okay - you must be on linux - just tried on an ubuntu VM and able to reproduce

**Comment by jeromecovington** [comment]
Yep. I'm Ubuntu 15.10 at the moment.

**Comment by davidmarkclements** [comment]
yah okay - I know what it is - we have to run perf with sudo, which means the process runs with sudo which is a different environment and hence different env vars, fixing now

**Comment by davidmarkclements** [comment]
should be fixed: https://github.com/davidmarkclements/0x/commit/88eae6fc94c7fa7e2383055c7bf1a1d08c73a3cc

caveat is if sudoers sec. policy disallows use of -E flag (I think this is (hopefully) a rare enough case to ignore) 


2.2.5 released

**Comment by jeromecovington** [comment]
Yep that sorted it. Thanks!
