### ISSUE TITLE
0x not working with yarn berry

### ISSUE THREAD

**Issue by carlduevel** [davidmarkclements/0x#262]
I'd like to use 0x in a project with  a current yarn release (3.2.1).
0x behaves strangely in this environment. I can reproduce this
behavior with this very simple package.json:

```
{
  "name": "yarn_0x_test",
  "packageManager": "yarn@3.2.1",
  "dependencies": {
    "0x": "^5.3.1"
  },
  "scripts": {
    "0x": "0x -v"
  },
  "version": "0.0.0"
}
```

Running `yarn 0x` leads to no output and returns successfully.
Calling it with the version flag is just an example of course.
This happens for all other 0x executions too, but this is the 
simplest example.

**Comment by mcollina** [comment]
I'm not sure if we can help, we are not users of yarn berry
