### ISSUE TITLE
--kernel-tracing support for other platforms

### ISSUE THREAD

**Issue by feedthejim** [davidmarkclements/0x#268]
hey,

Love the tool! I was wondering: how much work would it be to add kernel tracing support for mac os? If small enough, could support be added?

**Comment by mcollina** [comment]
We had --kernel-tracing support for Mac OS X, however Apple stopped supporting the feature we were using due to security. It would likely bit quite a feat to get it back supported.

I would love to see a PR that adds it but it's beyond the maintainers to tackle such a project.

**Comment by mcollina** [comment]
I think you'd need a Linux machine to properly optimize the lower levels of your application.
