### ISSUE TITLE
Demo link 404

### ISSUE THREAD

**Issue by mradbourne** [davidmarkclements/0x#282]
The README contains a link to an interactive flamegraph demo - http://davidmarkclements.github.io/0x-demo/
The demo is currently not found. This link responds with a 404.

**Comment by slhck** [comment]
This is still an issue — may I ask why you closed it?

**Comment by mradbourne** [comment]
@slhck It was a duplicate of #277 and #279. I'm assuming a fix isn't planned (in the short term at least).
