### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by behrad** [davidmarkclements/0x#32]
After Ctrl+C ing, I'm getting this

```
==== JS stack trace =========================================
Security context: 0x30b7876b4629 <JS Object>
    1: Join(aka Join) [native array.js:154] [pc=0x57634058ad8] (this=0x30b7876041b9 <undefined>,o=0x146ef8038981 <JS Array[14]>,v=14,C=0x146ef807bb01 <String[34]\: ,\n                                >,B=0x30b787695311 <JS Function ConvertToString (SharedFunctionInfo 0x30b78764a059)>)
    2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:331] [pc=0x5763405794a] (this=0x30b7876041b9 <undefin...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted
```

I'm on node v4.3.1, 0x 2.2.6 & 24G of memory.

**Comment by davidmarkclements** [comment]
This is perhaps a really huge flamegraph? Is this happening in every case or for a particular case (i..e have you tried profiling somethign else and did it work?) 

For the memory thing, try this: https://github.com/davidmarkclements/0x/issues/27#issuecomment-205764467

**Comment by behrad** [comment]
My stacks.*.out files are 130-440 Mb (multi minutes), the original one was 3.4 Gb (around 15minutes), it seems the error's been occurred after stack.out files generated.
I'm trying to do `0x -c gen` on them... let's see what happens

**Comment by davidmarkclements** [comment]
if you can get it working let me know, if not perhaps you could upload your stacks and I'll take a look?

**Comment by behrad** [comment]
I generated a file containing multiple seconds cut of my runtime load, Can you help me how to read it to find my high-load sections of code?

**Comment by behrad** [comment]
My file is available here http://ws.adpdigital.com/mobile/profile-115379.tar.gz
@davidmarkclements

**Comment by davidmarkclements** [comment]
- closing as issue was resolved
