### ISSUE TITLE
Error with generating flamegraphs when starting server using babel require hook

### ISSUE THREAD

**Issue by craigkj** [davidmarkclements/0x#34]
Hi there,

There appears to be a problem with generating the flamegraphs after profiling a node app using the babel require hook (https://babeljs.io/docs/setup/#installation).

```javascript
require('babel-register');
// Setup my server and start it
```

After terminating the app a `Unable to find map file!` and the waiting clock hangs indefinitely. This is identical to the bug found here: https://github.com/davidmarkclements/0x/issues/33 which I debugged a little further to try and pin down the problem.

The following note from the babel documentation possibly indicates the problem:

```
The require hook automatically hooks itself into all node requires. This will pollute the global scope and introduce conflicts. Because of this it's not suitable for libraries, if however you're writing an application then it's completely fine to use.
```

**Comment by davidmarkclements** [comment]
Yah we need to figure out an elegant way to co-exist, or at least a user friendly work around

Needs research, cc @mcollina @lucamaraschi @eljefedelrodeodeljefe

**Comment by craigkj** [comment]
@davidmarkclements

One possible work around is to pre transpile the app using the babel CLI and then remove the reference to the require hook for the duration of the profiling. Using the require hook in production is now (fairly newly) recommended against so I think a work around is fine.

The above work around worked for me and i'm now getting the flamegraphs generated as expected, which is glorious.

I'm happy to compile an example and some documentation/notes and PR them to the app if you would like?

**Comment by davidmarkclements** [comment]
@craigkj that would be very much welcome and appreciated - thanks for offering :bowtie:

**Comment by davidmarkclements** [comment]
covered by #35
