### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tmjam** [davidmarkclements/0x#36]
I get this error when 0x tries to generate the flame graph. More specifically it errors when doing `JSON.stringify` as the json size is large and thus causes the overflow. Is there a way to solve this issue by using something like `JSON.prune()` ?

**Comment by davidmarkclements** [comment]
Hey @tmjam see https://github.com/davidmarkclements/0x/issues/27#issuecomment-205764467 and also #28

**Comment by tmjam** [comment]
Thank you, you are awesome and great presentation at nodesummit :)
