### ISSUE TITLE
Empty stacks.<pid>.out

### ISSUE THREAD

**Issue by ergomatikus** [davidmarkclements/0x#38]
After executing
>\> 0x --trace-info node test.js
Profiling^C[ perf record: Woken up 1 times to write data ]
Caught SIGINT, generating flamegraph WARNING: The /tmp/perf-pi50u.data file's data size field is 0 which is unexpected.
Was the 'perf record' command properly terminated?
[ perf record: Captured and wrote 0.055 MB /tmp/perf-pi50u.data (138 samples) ]

and checking result:
>\> ll profile-28897/
total 376
drwxrwxr-x  2 user user   4096 Aug 24 14:33 ./
drwxr-xr-x 16 user user   4096 Aug 24 14:33 ../
-rw-rw-r--  1 user user 370134 Aug 24 14:33 flamegraph.html
-rw-rw-r--  1 user user     42 Aug 24 14:33 stacks.28897.json
-rw-rw-r--  1 user user      0 Aug 24 14:33 stacks.28897.out

we found that stacks.28897.out is empty

Our test.js looks like:
```
loop();
function loop() {
	var i;
	for(i=0;i<1000;i++) {
	}
	setTimeout(loop,100);
}
```
Our software versions:
>0x: 2.2.8
Ubuntu: 16.04.1 
Kernel: 4.4.0-34-generic
node: v4.4.7
perf: 4.4.15

**Comment by NicolaOrritos** [comment]
Same issue here:
> 0x: 2.2.8
> Arch Linux
> Kernel: 4.5.4
> Node: 6.2.2
> perf: 4.7

**Comment by NicolaOrritos** [comment]
Just found a solution: sending SIGTERM instead of SIGINT works as expected.  
I'm only speculating about this, but I think relying on SIGINT (and hence relying on CTRL+C) is a bad idea because it's an "immediate kill" signal and thus I think perf is killed before producing any output.

**Comment by mcollina** [comment]
@NicolaOrritos currently we are preloading https://github.com/davidmarkclements/0x/blob/master/soft-exit.js, so that SIGINT calls `process.exit(0)`. I think that for some reason that is not called on your example. We need `process.exit(0)` because otherwise it is probably that it does not generate the map file.

**Comment by NicolaOrritos** [comment]
Yeah, sounds right: I'm profiling a restify REST web-service with many helpers that monitor performance and critical anomalies at runtime. Maybe one of them (or maybe restify itself) is interfering with the soft-exit wrapper. I'll try to look into it further.

**Comment by NicolaOrritos** [comment]
@mcollina Nevermind my first comment about "SIGINT" being an "immediate kill": I mistook it for "SIGKILL", sorry.

**Comment by davidmarkclements** [comment]
Probably related to #33 and #34 (regardless of whether Babel is being used). We need to find an absolute solution here that avoids third party modifications - or failing that we need to document the conflicting cases

**Comment by mcollina** [comment]
@NicolaOrritos could you find a solution for your case?

@davidmarkclements we might just have a couple of switch options in `0x` for the most popular cases (maybe).

**Comment by NicolaOrritos** [comment]
@mcollina Not really, no. Aside from sending SIGTERM I couldn't get another solution.
Nor I found a path in my (complex) REST service that could _steal_ the SIGINT or SIGTERM handling from the soft-exit handle.
What else can I try to unravel this?

**Comment by davidmarkclements** [comment]
You can manually require (or copy) the soft exit code, and try it in different places (i.e. after all other requires, or maybe even after a setImmediate)

**Comment by NicolaOrritos** [comment]
Going to try it @davidmarkclements. Thanks!

**Comment by mcollina** [comment]
_maybe_ the solution might be to call `server.close(function () { process.exit(0) })` if you get `SIGINT`.

It worked for me in the past.

**Comment by NicolaOrritos** [comment]
I tried both but it resulted on the same issue ("INSTANCE_NAME" is needed by my service for starting):
```Bash
sudo INSTANCE_NAME=APTE DEBUG=0x* 0x --trace-info lib/main.js

[...]

^C[ perf record: Woken up 1 times to write data ]
  0x Caught SIGINT, generating flamegraph +0ms
Caught SIGINT, generating flamegraph WARNING: The /tmp/perf-bvyy8t.data file's data size field is 0 which is unexpected.
Was the 'perf record' command properly terminated?
  0x begin rendering +48ms
  0x:stack-convert serializing samples +7ms
  0x:stack-convert samples serialized +2ms
  0x converted stacks to intermediate format +2ms
[ perf record: Captured and wrote 0.236 MB /tmp/perf-bvyy8t.data (405 samples) ]
  0x flamegraph generated +378ms
  0x tidying up +0ms
file:///opt/vpweb/profile-27629/flamegraph.html 

  0x exiting +2ms
  0x done rendering +0ms
```

**Comment by davidmarkclements** [comment]
Closing for now as @NicolaOrritos has a worm around and the not working in same cases is a known master issue
