### ISSUE TITLE
Feature: Start / Stop profiling 

### ISSUE THREAD

**Issue by megastef** [davidmarkclements/0x#40]
Hi, I'm investigating a growing CPU usage, which happens after a few days. 
It would be interesting to start such a process with 0x and after a few days, when the CPU grows, it would be nice to send somehow a command or signal to start/stop profiling for a short time. 

Or can you recommend any other tool for such a task (possibly without source code modification, or opening ports on a production machine)?

**Comment by mcollina** [comment]
In practice we can't, the explanation is a bit long, and it is related to how `perf` and `perf-basic-prof` works, and all the little hacks we do to generate the flamegraph. `0x` is a tool for development.

What you want is dtrace on SmartOS. Or even Linux Tracing, but it might require some tool to be written.

**Comment by davidmarkclements** [comment]
..was just about to say the same thing - I've not found a way to "connect" perf to a running node process (dtrace can though)

We could switch out perf for another tool to get that functionality, but you still have the --perf-basic-prof flag enabled so it's probably not suitable for production (as @mcollina says)
