### ISSUE TITLE
Empty Flamegraph

### ISSUE THREAD

**Issue by jphalimi-intel** [davidmarkclements/0x#41]
I am using the following command:

`0x app.js`

The profiling starts, unfortunately the Flamegraph generated keeps being empty.  I followed the steps presented in the tutorial.

0x version 2.2.8
Ubuntu 16.04 (perf v4.4.16)

Attachment: output of the command:
`DEBUG=* 0x  app.js > /dev/null`
[output.txt](https://github.com/davidmarkclements/0x/files/473501/output.txt)

Attachment: stacks file, that is empty (zipped):
[stacks.zip](https://github.com/davidmarkclements/0x/files/473508/stacks.zip)

Is there something obvious I am missing? :-)

Thanks,

Jp

**Comment by davidmarkclements** [comment]
Hey @jphalimi-intel

* did it generate the actual flamegraph successfully though? 
* if on linux do you have perf installed
* have you tried the `--stacks-only` flag (if all you want is stacks - https://github.com/davidmarkclements/0x#production-servers)
* https://github.com/davidmarkclements/0x/issues/34 and https://github.com/davidmarkclements/0x/issues/33 may provide clues to help you figure out the issue

**Comment by jphalimi-intel** [comment]
@davidmarkclements Yes, the flamegraph.html was generated successfully, the file is here:
[flamegraph.zip](https://github.com/davidmarkclements/0x/files/475602/flamegraph.zip)

As mentioned previously, perf is installed (version 4.4.16).

If I try --stacks-only, the stacks.out is the only file generated, and it is empty.

I had a look at #34 and #33 but I could not find anything that helped me with the issue. I don't have any errors generated, even with DEBUG=*

**Comment by davidmarkclements** [comment]
what I'm guessing is happening, there's something getting in the way of 
https://github.com/davidmarkclements/0x/blob/master/soft-exit.js

That file is injected into your process - we need it there to successfully generate stacks

If another library is preventing that from happening (#33 / #34 related to this scenario) then you wont get stack output - it's quirk of the interaction between node and perf. 

@mcollina - anything to add?

**Comment by mcollina** [comment]
I agree that this looks like #33 or #34.

Were you able to replicate this issue using a test script, or just your application?

**Comment by davidmarkclements** [comment]
closing for now as we can't know more without looking at code, @jphalimi-intel feel free to contact me personally

**Comment by jphalimi-intel** [comment]
I will try to look closer at #33 and #34. If I can t solve my problem after that, I will contact you. Thanks for your prompt answers.

**Comment by david-martin** [comment]
Can we re-open this issue?

I'm seeing this on Fedora 24 (using the slow-rest-api app)
Some additional info that may be relevant.

```
DEBUG=0x,0x:stack-convert 0x --trace-info index.js 
Profiling^C[ perf record: Woken up 8 times to write data ]
  0x Caught SIGINT, generating flamegraph +0ms
Caught SIGINT, generating flamegraph WARNING: The /tmp/perf-3ns4rp.data file's data size field is 0 which is unexpected.
Was the 'perf record' command properly terminated?
  0x begin rendering +48ms
  0x:stack-convert serializing samples +4ms
  0x:stack-convert samples serialized +1ms
  0x converted stacks to intermediate format +0ms
[ perf record: Captured and wrote 2.117 MB /tmp/perf-3ns4rp.data (5423 samples) ]
  0x flamegraph generated +297ms
  0x tidying up +0ms
file:///home/dmartin/nodeconfeu2016/slow-rest-api/profile-13531/flamegraph.html

  0x exiting +0ms
  0x done rendering +0ms
```

```
autocannon -d 5 -c 100 -l http://localhost:3000/a 
Running 5s test @ http://localhost:3000/a
100 connections

Stat         Avg       Stdev    Max      
Latency (ms) 165.65    11.32    243      
Req/Sec      592.8     33.2     614      
Bytes/Sec    756.94 kB 44.45 kB 819.2 kB 

Percentile      Latency (ms)      
50              163               
75              166               
90              176               
99              195               
99.9            238               
99.99           243               
99.999          243               

3k requests in 5s, 3.81 MB read
```

I'm looking into this error specifically, which hints at a timing issue around the `perf script` cmd being executed

```
Caught SIGINT generating flamegraph WARNING: The /tmp/perf-3ns4rp.data file's data size field is 0 which is unexpected.
Was the 'perf record' command properly terminated?
```

Note the perf file is actually greater than 0 in size, but might not have it's contents written or flushed at the time it's being read by 0x
```
ls -l /tmp/perf-3ns4rp.data
-rw-------. 1 root root 2226512 Oct 17 21:29 /tmp/perf-3ns4rp.data
```
