### ISSUE TITLE
Do all output to stderr

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/0x#42]
So that redirecting logs to `/dev/null` hide stuff.

**Comment by davidmarkclements** [comment]
I think possibly a long term solution is a sort of status bar affair in the terminal, that separates flamegraph generation status output from stdout and stderr

**Comment by mcollina** [comment]
I think we should be able to pass-through (or not) the output of the tested process, maybe a `--silence-child` flag.

**Comment by davidmarkclements** [comment]
also need to document the `-q` flag
