### ISSUE TITLE
`clockface` binary not necessarily in `node_modules`

### ISSUE THREAD

**Issue by isiahmeadows** [davidmarkclements/0x#43]
Because of npm 3's tree shaking feature, the `clockface` binary isn't necessarily in `node_modules`, and thus [this function](https://github.com/davidmarkclements/0x/blob/master/index.js#L396-L400) will normally fail. You'll have to recursively find it now because of it (and BTW, when installing locally, this issue will normally appear unless an incompatible `clockface` is already required elsewhere).

**Comment by isiahmeadows** [comment]
My short-term workaround is just creating a `node_modules/.bin/clockface` post-install that links it to this.

**Comment by davidmarkclements** [comment]
I think I'll just get rid of it, it's more trouble than it's worth really
