### ISSUE TITLE
print progress bar while generating the flamegraph

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/0x#51]
As it can be a long process, we should notify the user of the status.

**Comment by yoshuawuyts** [comment]
This package might come in useful -
https://github.com/watson/progress-string; simple under the hood too

**Comment by davidmarkclements** [comment]
the real problem with this is it's non-trivial. generation is synchronous, event loop blocks - which is fine for the main case. But it does mean it's not possible to update a terminal progress bar without changing the way we generate. 

Initially I had the clock - that had to run as a separate process, and it was just to irksome to manage the two processes (like when the generation crashed for some reason but the clock stayed alive)

**Comment by davidmarkclements** [comment]
this is now a lot more possible in v4
