### ISSUE TITLE
DeprecationWarning: Using Buffer without `new` will soon stop working

### ISSUE THREAD

**Issue by alice0meta** [davidmarkclements/0x#52]
0x prints this error message: (node:49959) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by davidmarkclements** [comment]
thanks @alice0meta - we'll get round to this, (providing it's not a sub-dep that hasn't also updated yet, in which case we'll update subdep when it's resolved the deprecation notice) 

0x will still work fine for now - fwiy deprecating Buffer without new was a terrible idea that's going to affect a lot of people unnecessarily

**Comment by yoshuawuyts** [comment]
chances are big this'll be reverted as breakage throughout npm is severe
and it can easily be resolved in other ways

**Comment by davidmarkclements** [comment]
cf - https://twitter.com/davidmarkclem/status/801896080002711552

**Comment by mcollina** [comment]
Not needed, deprecation was reversed in core.
