### ISSUE TITLE
Running on OSX with NPM3 does not work.

### ISSUE THREAD

**Issue by lostthetrail** [davidmarkclements/0x#54]
profile_1ms.d is being referenced absolutely in the directory structure for NPM2. In NPM3, it is placed in the node_modules/.bin directory, rather than the previous home of node_modules/0x/.bin directory.

https://github.com/davidmarkclements/0x/blob/master/index.js#L48

I will try to toss together a PR.

@davidmarkclements - Thanks for the on-spot debugging at the conference yesterday. Turns out I had two issues, XCode and then this issue.

**Comment by mcollina** [comment]
@lostthetrail I am running this with npm v3 and node v6 and v7, and I have no problem. I'm ok with the change, I just would like to understand what's the situation.

**Comment by mcollina** [comment]
I think a better approach would be to export `perfSym.pathToProfile1msd` path from https://github.com/davidmarkclements/perf-sym, and stop relying on npm/paths/env variables.

**Comment by davidmarkclements** [comment]
I'm going to merge @lostthetrails PR for now, but @mcollina let's discuss the whole thing while we're here in Austin

**Comment by lostthetrail** [comment]
@mcollina Did you remove and re-install your global or project node_modules?

**Comment by mcollina** [comment]
oooh I only install it globally, that's why.
