### ISSUE TITLE
Document memory constraint solutions

### ISSUE THREAD

**Issue by lostthetrail** [davidmarkclements/0x#56]
Add the following to README:

If your node instance is dying due to "RangeError: Maximum call stack size exceeded", add more memory to Node:
```
--stack-size=8024
```

If your flamegraph.html is reporting "RangeError: Maximum call stack size exceeded" to console, add more memory to Chrome:
```
--js-flags="--stack-size 8024"
```

**Comment by mcollina** [comment]
Thanks! Would you like to send a PR for the README? Maybe with a `FAQ` sections?

**Comment by davidmarkclements** [comment]
thanks @lostthetrail !
