### ISSUE TITLE
Optimzed and Not Optimized

### ISSUE THREAD

**Issue by mattbajorek** [davidmarkclements/0x#58]
I have been reading the description and can not find any information explaining optimized and not optimized.  Would anybody be able to provide some helpful information or direction to information.  Thanks!

**Comment by davidmarkclements** [comment]
hey @mattbajorek - that's a fair point

it relates to v8 internals, you have optimized functions (which is different to inlined), and then you have non-optimizable, and also deoptimized. 

On the flamegraph we can show optimized and not optimized (which is either deopted or not possible to opt)

v8 has various optimizations it may apply to a function

a simple one is if you're passing numbers into a function v8 assumes that the numbers are 32bit integers - so uses smi's (small integers) - the moment a number that surpasses 32bit capacity is passed to the function, the function will deoptimize (and may possibly reopt if all subsequent numbers are 64bit) 

another example is polymorphism, v8 watches for function inputs, and if the type of input is consistent it can optimize the function in a certain way - however if the type keeps changing, the function will not be optimizable 

You can use the `--trace-opt` and `--trace-deopt` flags with node to get detailed trace output

**Comment by mcollina** [comment]
can we add this to the readme?

**Comment by davidmarkclements** [comment]
I'm torn on that - we have to define base level of knowledge - I think if we can find a link and simply link from readme to it when talking about them
