### ISSUE TITLE
+ - buttons on top of the search input in flamegraph.html

### ISSUE THREAD

**Issue by alessioalex** [davidmarkclements/0x#6]
I don't have a print screen to show you, but I cannot see what I type in the input box because the buttons are on top of it.

**Comment by davidmarkclements** [comment]
Can I get browser and screensize?

**Comment by alessioalex** [comment]
Here you go, my bad for not including them in the initial ticket:

```
Google Chrome Version 48.0.2564.109 (64-bit)

Resolution: 1280 x 1024

→ uname -a
Linux DXBU-JKSDJ32 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mcollina** [comment]
is this still an issue @alessioalex? I _never seen it_.

**Comment by crostine** [comment]
it is for me:
![capture](https://cloud.githubusercontent.com/assets/5873080/24206322/2db06d1c-0f1e-11e7-88ce-3404e6d1426b.PNG)

windows 10 pro
chrome Version 56.0.2924.87
screen resolution 1200*1920

the profile was generated on a linux machine with no desktop, so i copied it to my windows machine
