### ISSUE TITLE
Support specifying output directory

### ISSUE THREAD

**Issue by knksmith57** [davidmarkclements/0x#60]
It'd be nice if it were possible to specify the output directory to use instead of [generating it on the fly using the `PID`](https://github.com/davidmarkclements/0x/blob/4074aa2021adaef208d9fc9fd239e8e68f38df3a/index.js#L37).

Especially in a docker world where specific files and directories are mounted into containers, having non-deterministic paths can be a pain.

Something like `-O / --output-dir` would be awesome 🙂

Thanks for putting out such a quality tool!

**Comment by mcollina** [comment]
Good idea, what about a PR?

**Comment by knksmith57** [comment]
@mcollina good idea! Opened #61
