### ISSUE TITLE
improve svg rendering

### ISSUE THREAD

**Issue by davidmarkclements** [davidmarkclements/0x#62]
just pushed out an --svg flag to create a flamegraph.svg file

we can improve this in two ways

1. remove all the title elements, since it's intended for use as a static image
2. remove all <foreignobject><div>text</div></foreignobject> occurrences and replace them with <text> elements that are position over the top of the <rects>

**Comment by yoshuawuyts** [comment]
Or option C: use Firefox's new flamegraph canvas renderer https://github.com/devtools-html/perf.html/pull/702/files :grin:

**Comment by davidmarkclements** [comment]
😮

@mcollina I think we should carve some time to look into this if/when we look at UI skinning

**Comment by davidmarkclements** [comment]
removed from v4, wontfix
