### ISSUE TITLE
trouble navigating the flamegraph

### ISSUE THREAD

**Issue by crostine** [davidmarkclements/0x#65]
so i captured the following data:
![capture](https://cloud.githubusercontent.com/assets/5873080/24206582/f186d0b4-0f1e-11e7-9481-2908e5e33d0f.PNG)

when i zoom in (+button) nothing happens. (unless i have already zoomed out)
when i zoom out(-button)  the image becomes smaller.

i can click an orange pixel and it turns out to be some call somewhere in the program.
but i have no clue how to properly navigate through the output.

**Comment by hvhallmann** [comment]
I got the same issue, maybe our stack is too big :)

**Comment by davidmarkclements** [comment]
hehehe 

yeah sorry guys - ironically the UI needs some serious performance tuning for stacks that big

PR's always welcome

In the meantime, are you able to isolate suspect parts and flamegraph those instead?

As an aside, if the flamegraph is huge, your app may benefit from being deconstructed into services
