### ISSUE TITLE
Mac: Prof process does not die

### ISSUE THREAD

**Issue by pgte** [davidmarkclements/0x#66]
In some of my executions, after the child process exits, the profiling process does not die.
One interim solution was to send a SIGKILL instead of a SIGINT to the profiling process [here](https://github.com/davidmarkclements/0x/blob/master/index.js#L152).
Have you seen this happening before, and if so, did you get a sense of why this may happen?

Node v6.9.2
MacOS 10.12.3.

Thanks so much, great module BTW!

**Comment by mcollina** [comment]
This is a bit weird, but I saw this as well. I do not know why. Maybe we can do a setTimeout and send SIGKILL if it is not dead?

Would you mind to send a PR?

**Comment by pgte** [comment]
@mcollina on it.
