### ISSUE TITLE
a way of providing perf/dtrace output to generate flamegraphs

### ISSUE THREAD

**Issue by bengl** [davidmarkclements/0x#69]
I'd like a way of providing input files (or stdin) containing already-generated perf or dtrace data, so that I can use the viewer in kind of a standalone mode. I often find myself wanting to do different things to generate the data (for example, running `perf record` against an already running process).

**Comment by mcollina** [comment]
That'd be handy, but one of the problem this fixes are symbols. On Mac OS X there are no symbols from dtrace. However it would be cool to be able to collect a perf output from Linux, and then generate it on the Mac. Would you like to send us a PR?

**Comment by davidmarkclements** [comment]
--collect-only and --visualize-only should cater to this
