### ISSUE TITLE
Passing arguments to the script being executed fails when `node` not specified

### ISSUE THREAD

**Issue by edmorley** [davidmarkclements/0x#70]
Using 0x 2.4.2, nodejs 8.1.0 under Ubuntu 16.04, passing options to the script being run fails with an unclear error message:
```
$ 0x ./node_modules/.bin/oao bootstrap
module.js:487
    throw err;
    ^

Error: Cannot find module '/home/vagrant/neutrino-dev/bootstrap'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

By experimentation I found that the alternative form works however:
```
$ 0x node ./node_modules/.bin/oao bootstrap
...
```

I'm presuming both forms are expected to work?

Many thanks!

**Comment by mcollina** [comment]
@edmorley no, only the second one is supported atm. But if you want to send a PR we'll be very happy to review it!

**Comment by edmorley** [comment]
Ah ok - I thought either were, since the docs say "When node flags aren't required, we can use the shorthand form" -- and I'd interpreted "node flags" to be "nodejs runtime options" rather than "options passed to the script itself".

**Comment by davidmarkclements** [comment]
Fixed in v3
