### ISSUE TITLE
node-options broken on Linux

### ISSUE THREAD

**Issue by jcape** [davidmarkclements/0x#79]
It's not actually added to the array of arguments that's handed to perf/sudo anywhere.

**Comment by davidmarkclements** [comment]
cc @mcollina 

I really think we should roll back to how it was before, especially if script args are also broken (as #80) indicates

**Comment by mcollina** [comment]
The previous code was unmaintainable. Let’s fix this.

**Comment by mcollina** [comment]
Fixed in 2.5.3.

**Comment by jcape** [comment]
Thanks guys
