### ISSUE TITLE
maximum call stacktrace when open flamegraph.html

### ISSUE THREAD

**Issue by tuananh** [davidmarkclements/0x#82]
How can i fix this?

I run my app with `0x index` and then run the test suite. terminate `0x` process after but i can't view the flamegraph.html

version 2.5.2

![image](https://user-images.githubusercontent.com/627278/31302828-315a7c84-ab2f-11e7-8727-859a2e7b1d17.png)

**Comment by davidmarkclements** [comment]
see https://github.com/davidmarkclements/0x#memory-issues

bear in mind (and this needs to be clarified now) you should pass the `--stack-size=8024` 
using `--node-options`, e.g.  `--node-options="--stack-size=8024"`
