### ISSUE TITLE
Does not work on Linux if a program ends before you kill it 

### ISSUE THREAD

**Issue by mafintosh** [davidmarkclements/0x#90]
On Linux, try profiling

``` js
for (var i = 0; i < 100; i++) {
  Math.random()
}
```

The program ends before you can `ctrl-c` the process and it dies crashes with

```
kill: sending signal to 15563 failed: No such process
```

consistently. Seems to work on Mac tho.

**Comment by mcollina** [comment]
this is a very nice bug!

**Comment by mcollina** [comment]
On Mac OS X, we are pretty stubborn in killing the process:
https://github.com/davidmarkclements/0x/blob/master/platform/sun.js#L115-L126

On Linux, we have to use a completely different strategy:
https://github.com/davidmarkclements/0x/blob/master/platform/linux.js#L106-L108

There is _some_ history on why this happens (https://github.com/davidmarkclements/0x/pull/74/  https://github.com/davidmarkclements/0x/pull/45).
I think we should just add some error handlers to the `spawn` call?

**Comment by mafintosh** [comment]
@davidmarkclements isn't module loading sync? ie why would nextTick not be enough?

**Comment by davidmarkclements** [comment]
it's a separate process – delay is for delay before spinning up prof/dtrace
