### ISSUE TITLE
Top right UI broken on Firefox

### ISSUE THREAD

**Issue by yoshuawuyts** [davidmarkclements/0x#94]
The search bar buttons seem to be slightly oddly styled on Firefox. On Linux, but not sure if that's relevant.

![2018-01-25-102607_1920x1080](https://user-images.githubusercontent.com/2467194/35374337-696495c4-01dd-11e8-8781-0b36f04c626f.png)

**Comment by davidmarkclements** [comment]
v4 specified as supporting chrome only, firefox fixes welcome though
