### ISSUE TITLE
libuv symbols on Linux not being filtered as cpp

### ISSUE THREAD

**Issue by yoshuawuyts** [davidmarkclements/0x#95]
When running 0x on Linux, the `"core"` filter does not strip the `uv_*` / `node::`, etc. symbols. This makes it tricky to look solely at userland core.

![2018-01-25-144052_1920x1080](https://user-images.githubusercontent.com/2467194/35374444-dffd6558-01dd-11e8-895f-daaf60cdf18b.png)

**Comment by davidmarkclements** [comment]
todo: check this is still the case with v4
