### ISSUE TITLE
Example of working command line with --json-stacks

### ISSUE THREAD

**Issue by kirillgroshkov** [davidmarkclements/0x#96]
`--json-stacks` is not working for me. Can someone provide a working example of command line that had it working (producing a *.json file in the output directory)?

What I'm trying to achieve is in the end to load flamecharts into Chrome DevTools. I understand this will require one more step to process json into .cpuprofile, but now I want to get this json file.

**Comment by davidmarkclements** [comment]
looks like it's a bug, I'm looking into it

**Comment by davidmarkclements** [comment]
@kirillgroshkov this is fixed in v3.1.1 

re command, best way would be

```sh
0x --collect-only --json-stacks app.js
```
